
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```
~~The text continues here.~~

GitHub repository: <https://github.com/phuoc-tn/IODS-project>

***How are you feeling right now?***

Quite **tired**.

***What do you expect to learn?***

How/when/why to do certain statistical analyses. Maybe new tricks to use in R.

***Where did you hear about the course?***

My doctoral school informed me in an email.

*How did it work as a "crash course" on modern R tools and using RStudio?*

Quite intensive.

***Which were your favorite topics?***

Data parsing, using partial matches to find columns.

***Which topics were most difficult?***

Transposing data frames.

***Some other comments on the book and our new approach of getting started with R Markdown etc.?***

The online book is a great resource! I will definitely bookmark it for future use.

